<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="TaleLoom.Core">
        <HintPath>..\TaleLoom\bin\Debug\net10.0\TaleLoom.Core.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TaleLoom.Core\TaleLoom.Core.csproj" />
    </ItemGroup>

</Project>
