<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.2"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.2"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TaleLoom.Core\TaleLoom.Core.csproj" />
      <ProjectReference Include="..\TaleLoom.Infrastructure\TaleLoom.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Entities\Fields\TextFieldEditor.axaml.cs">
        <DependentUpon>TextFieldEditor.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Entities\Fields\ImageFieldEditor.axaml.cs">
        <DependentUpon>ImageFieldEditor.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Entities\Fields\UrlFieldEditor.axaml.cs">
        <DependentUpon>UrlFieldEditor.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Entities\Fields\ReferenceFieldEditor.axaml.cs">
        <DependentUpon>ReferenceFieldEditor.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

</Project>
